export const CHECK_REDUX_NO_PAYLOAD = 'CHECK_REDUX_NO_PAYLOAD';
export const CHECK_REDUX_HAS_PAYLOAD = 'CHECK_REDUX_HAS_PAYLOAD';

export const IS_OPEN_MODAL = 'IS_OPEN_MODAL';
export const IS_CLEAR_MODAL = 'IS_CLEAR_MODAL';

export const IS_SET_LOADING = 'IS_SET_LOADING';
export const IS_CLEAR_LOADING = 'IS_CLEAR_LOADING';